// Copyright 2024 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

#undef napi_addon_register_func
#undef napi_module
#undef napi_add_env_cleanup_hook
#undef napi_remove_env_cleanup_hook
#undef napi_async_execute_callback
#undef napi_async_complete_callback
#undef napi_async_work
#undef napi_threadsafe_function
#undef napi_env
#undef napi_env__
#undef napi_value
#undef napi_value__
#undef napi_ref
#undef napi_ref__
#undef napi_handle_scope
#undef napi_handle_scope__
#undef napi_escapable_handle_scope
#undef napi_escapable_handle_scope__
#undef napi_callback_info
#undef napi_callback_info__
#undef napi_deferred
#undef napi_deferred__
#undef napi_default
#undef napi_writable
#undef napi_enumerable
#undef napi_configurable
#undef napi_static
#undef napi_default_method
#undef napi_default_jsproperty
#undef napi_property_attributes
#undef napi_undefined
#undef napi_null
#undef napi_boolean
#undef napi_number
#undef napi_string
#undef napi_symbol
#undef napi_object
#undef napi_function
#undef napi_external
#undef napi_bigint
#undef napi_valuetype
#undef napi_int8_array
#undef napi_uint8_array
#undef napi_uint8_clamped_array
#undef napi_int16_array
#undef napi_uint16_array
#undef napi_int32_array
#undef napi_uint32_array
#undef napi_float32_array
#undef napi_float64_array
#undef napi_bigint64_array
#undef napi_biguint64_array
#undef napi_typedarray_type
#undef napi_tsfn_nonblocking
#undef napi_tsfn_blocking
#undef napi_threadsafe_function_call_mode
#undef napi_threadsafe_function_call_js
#undef napi_ok
#undef napi_invalid_arg
#undef napi_object_expected
#undef napi_string_expected
#undef napi_name_expected
#undef napi_function_expected
#undef napi_number_expected
#undef napi_boolean_expected
#undef napi_array_expected
#undef napi_generic_failure
#undef napi_pending_exception
#undef napi_cancelled
#undef napi_escape_called_twice
#undef napi_handle_scope_mismatch
#undef napi_callback_scope_mismatch
#undef napi_queue_full
#undef napi_closing
#undef napi_bigint_expected
#undef napi_date_expected
#undef napi_arraybuffer_expected
#undef napi_detachable_arraybuffer_expected
#undef napi_conflict_instance_data
#undef napi_context_scope_mismatch
#undef napi_status
#undef napi_callback
#undef napi_finalize
#undef napi_property_descriptor
#undef napi_extended_error_info
#undef napi_get_last_error_info
#undef napi_key_include_prototypes
#undef napi_key_own_only
#undef napi_key_collection_mode
#undef napi_key_all_properties
#undef napi_key_writable
#undef napi_key_enumerable
#undef napi_key_configurable
#undef napi_key_skip_strings
#undef napi_key_skip_symbols
#undef napi_key_filter
#undef napi_key_keep_numbers
#undef napi_key_numbers_to_strings
#undef napi_key_conversion
#undef napi_async_context__
#undef napi_async_context
#undef napi_callback_scope
#undef napi_callback_scope__
#undef napi_threadsafe_function_release_mode
#undef napi_tsfn_release
#undef napi_tsfn_abort

#undef napi_get_version
#undef napi_get_undefined
#undef napi_get_null
#undef napi_get_global
#undef napi_get_boolean
#undef napi_create_object
#undef napi_create_array
#undef napi_create_array_with_length
#undef napi_create_double
#undef napi_create_int32
#undef napi_create_uint32
#undef napi_create_int64
#undef napi_create_string_latin1
#undef napi_create_string_utf8
#undef napi_create_string_utf16
#undef napi_create_symbol
#undef napi_create_function
#undef napi_create_error
#undef napi_create_type_error
#undef napi_create_range_error
#undef napi_adjust_external_memory
#undef napi_typeof
#undef napi_get_value_double
#undef napi_get_value_int32
#undef napi_get_value_uint32
#undef napi_get_value_int64
#undef napi_get_value_bool
#undef napi_get_value_string_latin1
#undef napi_get_value_string_utf8
#undef napi_get_value_string_utf16
#undef napi_coerce_to_bool
#undef napi_coerce_to_number
#undef napi_coerce_to_object
#undef napi_coerce_to_string
#undef napi_get_prototype
#undef napi_get_property_names
#undef napi_set_property
#undef napi_has_property
#undef napi_get_property
#undef napi_delete_property
#undef napi_has_own_property
#undef napi_set_named_property
#undef napi_has_named_property
#undef napi_get_named_property
#undef napi_set_element
#undef napi_has_element
#undef napi_get_element
#undef napi_delete_element
#undef napi_define_properties
#undef napi_is_array
#undef napi_get_array_length
#undef napi_strict_equals
#undef napi_call_function
#undef napi_new_instance
#undef napi_instanceof
#undef napi_get_cb_info
#undef napi_get_new_target
#undef napi_define_class
#undef napi_wrap
#undef napi_unwrap
#undef napi_remove_wrap
#undef napi_create_external
#undef napi_get_value_external
#undef napi_create_reference
#undef napi_delete_reference
#undef napi_reference_ref
#undef napi_reference_unref
#undef napi_get_reference_value
#undef napi_open_handle_scope
#undef napi_close_handle_scope
#undef napi_open_escapable_handle_scope
#undef napi_close_escapable_handle_scope
#undef napi_escape_handle
#undef napi_throw
#undef napi_throw_error
#undef napi_throw_type_error
#undef napi_throw_range_error
#undef napi_is_error
#undef napi_is_exception_pending
#undef napi_get_and_clear_last_exception
#undef napi_is_arraybuffer
#undef napi_create_arraybuffer
#undef napi_create_external_arraybuffer
#undef napi_get_arraybuffer_info
#undef napi_is_typedarray
#undef napi_create_typedarray
#undef napi_get_typedarray_info
#undef napi_create_dataview
#undef napi_is_dataview
#undef napi_get_dataview_info
#undef napi_create_promise
#undef napi_release_deferred
#undef napi_is_promise
#undef napi_run_script
#undef napi_add_finalizer
#undef napi_set_instance_data
#undef napi_get_instance_data
#undef napi_get_last_error_info
#undef napi_add_env_cleanup_hook
#undef napi_remove_env_cleanup_hook
#undef napi_create_threadsafe_function
#undef napi_call_threadsafe_function
#undef napi_release_threadsafe_function
#undef napi_get_threadsafe_function_context
#undef napi_fatal_error
#undef napi_module_register
#undef napi_resolve_deferred
#undef napi_reject_deferred
#undef napi_fatal_exception
#undef napi_unref_threadsafe_function
#undef napi_ref_threadsafe_function
#undef napi_acquire_threadsafe_function
#undef napi_create_date
#undef napi_is_date
#undef napi_get_date_value
#undef napi_create_bigint_int64
#undef napi_create_bigint_uint64
#undef napi_create_bigint_words
#undef napi_get_value_bigint_int64
#undef napi_get_value_bigint_uint64
#undef napi_get_value_bigint_words
#undef napi_get_all_property_names
#undef napi_would_deadlock
#undef napi_no_external_buffers_allowed
#undef napi_cannot_run_js
#undef napi_create_async_work
#undef napi_queue_async_work
#undef napi_cancel_async_work
#undef napi_delete_async_work
