// Copyright 2024 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
//
// this file may need to be include multiple times

// node_api.h
#define napi_addon_register_func napi_addon_register_func_primjs
#define napi_module napi_module_primjs
#define napi_add_env_cleanup_hook napi_add_env_cleanup_hook_primjs
#define napi_remove_env_cleanup_hook napi_remove_env_cleanup_hook_primjs

// node_api_types.h
#define napi_async_execute_callback napi_async_execute_callback_primjs
#define napi_async_complete_callback napi_async_complete_callback_primjs
#define napi_async_work napi_async_work_primjs
#define napi_threadsafe_function napi_threadsafe_function_primjs

// js_native_api_types.h
#define napi_env napi_env_primjs
#define napi_env__ napi_env_primjs__
#define napi_value napi_value_primjs
#define napi_value__ napi_value_primjs__
#define napi_ref napi_ref_primjs
#define napi_ref__ napi_ref_primjs__
#define napi_handle_scope napi_handle_scope_primjs
#define napi_handle_scope__ napi_handle_scope_primjs__
#define napi_escapable_handle_scope napi_escapable_handle_scope_primjs
#define napi_escapable_handle_scope__ napi_escapable_handle_scope_primjs__
#define napi_callback_info napi_callback_info_primjs
#define napi_callback_info__ napi_callback_info_primjs__
#define napi_deferred napi_deferred_primjs
#define napi_deferred__ napi_deferred_primjs__

#define napi_default napi_default_primjs
#define napi_writable napi_writable_primjs
#define napi_enumerable napi_enumerable_primjs
#define napi_configurable napi_configurable_primjs
#define napi_static napi_static_primjs
#define napi_default_method napi_default_method_primjs
#define napi_default_jsproperty napi_default_jsproperty_primjs
#define napi_property_attributes napi_property_attributes_primjs

#define napi_undefined napi_undefined_primjs
#define napi_null napi_null_primjs
#define napi_boolean napi_boolean_primjs
#define napi_number napi_number_primjs
#define napi_string napi_string_primjs
#define napi_symbol napi_symbol_primjs
#define napi_object napi_object_primjs
#define napi_function napi_function_primjs
#define napi_external napi_external_primjs
#define napi_bigint napi_bigint_primjs
#define napi_valuetype napi_valuetype_primjs

#define napi_int8_array napi_int8_array_primjs
#define napi_uint8_array napi_uint8_array_primjs
#define napi_uint8_clamped_array napi_uint8_clamped_array_primjs
#define napi_int16_array napi_int16_array_primjs
#define napi_uint16_array napi_uint16_array_primjs
#define napi_int32_array napi_int32_array_primjs
#define napi_uint32_array napi_uint32_array_primjs
#define napi_float32_array napi_float32_array_primjs
#define napi_float64_array napi_float64_array_primjs
#define napi_bigint64_array napi_bigint64_array_primjs
#define napi_biguint64_array napi_biguint64_array_primjs
#define napi_typedarray_type napi_typedarray_type_primjs

#define napi_tsfn_nonblocking napi_tsfn_nonblocking_primjs
#define napi_tsfn_blocking napi_tsfn_blocking_primjs
#define napi_threadsafe_function_call_mode \
  napi_threadsafe_function_call_mode_primjs
#define napi_threadsafe_function_call_js napi_threadsafe_function_call_js_primjs

#define napi_ok napi_ok_primjs
#define napi_invalid_arg napi_invalid_arg_primjs
#define napi_object_expected napi_object_expected_primjs
#define napi_string_expected napi_string_expected_primjs
#define napi_name_expected napi_name_expected_primjs
#define napi_function_expected napi_function_expected_primjs
#define napi_number_expected napi_number_expected_primjs
#define napi_boolean_expected napi_boolean_expected_primjs
#define napi_array_expected napi_array_expected_primjs
#define napi_generic_failure napi_generic_failure_primjs
#define napi_pending_exception napi_pending_exception_primjs
#define napi_cancelled napi_cancelled_primjs
#define napi_escape_called_twice napi_escape_called_twice_primjs
#define napi_handle_scope_mismatch napi_handle_scope_mismatch_primjs
#define napi_callback_scope_mismatch napi_callback_scope_mismatch_primjs
#define napi_queue_full napi_queue_full_primjs
#define napi_closing napi_closing_primjs
#define napi_bigint_expected napi_bigint_expected_primjs
#define napi_date_expected napi_date_expected_primjs
#define napi_arraybuffer_expected napi_arraybuffer_expected_primjs
#define napi_detachable_arraybuffer_expected \
  napi_detachable_arraybuffer_expected_primjs
#define napi_conflict_instance_data napi_conflict_instance_data_primjs
#define napi_context_scope_mismatch napi_context_scope_mismatch_primjs
#define napi_status napi_status_primjs

#define napi_callback napi_callback_primjs
#define napi_finalize napi_finalize_primjs

#define napi_property_descriptor napi_property_descriptor_primjs
#define napi_extended_error_info napi_extended_error_info_primjs
#define napi_get_last_error_info napi_get_last_error_info_primjs

#define napi_key_include_prototypes napi_key_include_prototypes_primjs
#define napi_key_own_only napi_key_own_only_primjs
#define napi_key_collection_mode napi_key_collection_mode_primjs
#define napi_key_all_properties napi_key_all_properties_primjs
#define napi_key_writable napi_key_writable_primjs
#define napi_key_enumerable napi_key_enumerable_primjs
#define napi_key_configurable napi_key_configurable_primjs
#define napi_key_skip_strings napi_key_skip_strings_primjs
#define napi_key_skip_symbols napi_key_skip_symbols_primjs
#define napi_key_filter napi_key_filter_primjs
#define napi_key_keep_numbers napi_key_keep_numbers_primjs
#define napi_key_numbers_to_strings napi_key_numbers_to_strings_primjs
#define napi_key_conversion napi_key_conversion_primjs
#define napi_async_context__ napi_async_context_primjs__
#define napi_async_context napi_async_context_primjs
#define napi_callback_scope napi_callback_scope_primjs
#define napi_callback_scope__ napi_callback_scope_primjs__
#define napi_threadsafe_function_release_mode \
  napi_threadsafe_function_release_mode_primjs
#define napi_tsfn_release napi_tsfn_release_primjs
#define napi_tsfn_abort napi_tsfn_abort_primjs

#define napi_get_version napi_get_version_primjs
#define napi_get_undefined napi_get_undefined_primjs
#define napi_get_null napi_get_null_primjs
#define napi_get_global napi_get_global_primjs
#define napi_get_boolean napi_get_boolean_primjs

#define napi_create_object napi_create_object_primjs
#define napi_create_array napi_create_array_primjs
#define napi_create_array_with_length napi_create_array_with_length_primjs
#define napi_create_double napi_create_double_primjs
#define napi_create_int32 napi_create_int32_primjs
#define napi_create_uint32 napi_create_uint32_primjs
#define napi_create_int64 napi_create_int64_primjs
#define napi_create_string_latin1 napi_create_string_latin1_primjs
#define napi_create_string_utf8 napi_create_string_utf8_primjs
#define napi_create_string_utf16 napi_create_string_utf16_primjs
#define napi_create_symbol napi_create_symbol_primjs
#define napi_create_function napi_create_function_primjs
#define napi_create_error napi_create_error_primjs
#define napi_create_type_error napi_create_type_error_primjs
#define napi_create_range_error napi_create_range_error_primjs

#define napi_adjust_external_memory napi_adjust_external_memory_primjs

#define napi_typeof napi_typeof_primjs
#define napi_get_value_double napi_get_value_double_primjs
#define napi_get_value_int32 napi_get_value_int32_primjs
#define napi_get_value_uint32 napi_get_value_uint32_primjs
#define napi_get_value_int64 napi_get_value_int64_primjs
#define napi_get_value_bool napi_get_value_bool_primjs

#define napi_get_value_string_latin1 napi_get_value_string_latin1_primjs
#define napi_get_value_string_utf8 napi_get_value_string_utf8_primjs
#define napi_get_value_string_utf16 napi_get_value_string_utf16_primjs

#define napi_coerce_to_bool napi_coerce_to_bool_primjs
#define napi_coerce_to_number napi_coerce_to_number_primjs
#define napi_coerce_to_object napi_coerce_to_object_primjs
#define napi_coerce_to_string napi_coerce_to_string_primjs

#define napi_get_prototype napi_get_prototype_primjs
#define napi_get_property_names napi_get_property_names_primjs
#define napi_set_property napi_set_property_primjs
#define napi_has_property napi_has_property_primjs
#define napi_get_property napi_get_property_primjs
#define napi_delete_property napi_delete_property_primjs
#define napi_has_own_property napi_has_own_property_primjs
#define napi_set_named_property napi_set_named_property_primjs
#define napi_has_named_property napi_has_named_property_primjs
#define napi_get_named_property napi_get_named_property_primjs
#define napi_set_element napi_set_element_primjs
#define napi_has_element napi_has_element_primjs
#define napi_get_element napi_get_element_primjs
#define napi_delete_element napi_delete_element_primjs
#define napi_define_properties napi_define_properties_primjs

#define napi_is_array napi_is_array_primjs
#define napi_get_array_length napi_get_array_length_primjs

#define napi_strict_equals napi_strict_equals_primjs

#define napi_call_function napi_call_function_primjs
#define napi_new_instance napi_new_instance_primjs
#define napi_instanceof napi_instanceof_primjs

#define napi_get_cb_info napi_get_cb_info_primjs
#define napi_get_new_target napi_get_new_target_primjs

#define napi_define_class napi_define_class_primjs

#define napi_wrap napi_wrap_primjs
#define napi_unwrap napi_unwrap_primjs
#define napi_remove_wrap napi_remove_wrap_primjs

#define napi_create_external napi_create_external_primjs
#define napi_get_value_external napi_get_value_external_primjs

#define napi_create_reference napi_create_reference_primjs
#define napi_delete_reference napi_delete_reference_primjs
#define napi_reference_ref napi_reference_ref_primjs
#define napi_reference_unref napi_reference_unref_primjs
#define napi_get_reference_value napi_get_reference_value_primjs

#define napi_open_handle_scope napi_open_handle_scope_primjs
#define napi_close_handle_scope napi_close_handle_scope_primjs
#define napi_open_escapable_handle_scope napi_open_escapable_handle_scope_primjs
#define napi_close_escapable_handle_scope \
  napi_close_escapable_handle_scope_primjs
#define napi_escape_handle napi_escape_handle_primjs

#define napi_throw napi_throw_primjs
#define napi_throw_error napi_throw_error_primjs
#define napi_throw_type_error napi_throw_type_error_primjs
#define napi_throw_range_error napi_throw_range_error_primjs
#define napi_is_error napi_is_error_primjs

#define napi_is_exception_pending napi_is_exception_pending_primjs
#define napi_get_and_clear_last_exception \
  napi_get_and_clear_last_exception_primjs

#define napi_is_arraybuffer napi_is_arraybuffer_primjs
#define napi_create_arraybuffer napi_create_arraybuffer_primjs
#define napi_create_external_arraybuffer napi_create_external_arraybuffer_primjs
#define napi_get_arraybuffer_info napi_get_arraybuffer_info_primjs

#define napi_is_typedarray napi_is_typedarray_primjs
#define napi_create_typedarray napi_create_typedarray_primjs
#define napi_get_typedarray_info napi_get_typedarray_info_primjs

#define napi_create_dataview napi_create_dataview_primjs
#define napi_is_dataview napi_is_dataview_primjs
#define napi_get_dataview_info napi_get_dataview_info_primjs

#define napi_create_promise napi_create_promise_primjs
#define napi_release_deferred napi_release_deferred_primjs
#define napi_is_promise napi_is_promise_primjs

#define napi_run_script napi_run_script_primjs

#define napi_add_finalizer napi_add_finalizer_primjs

#define napi_set_instance_data napi_set_instance_data_primjs
#define napi_get_instance_data napi_get_instance_data_primjs

#define napi_add_env_cleanup_hook napi_add_env_cleanup_hook_primjs
#define napi_remove_env_cleanup_hook napi_remove_env_cleanup_hook_primjs

#define napi_create_threadsafe_function napi_create_threadsafe_function_primjs
#define napi_call_threadsafe_function napi_call_threadsafe_function_primjs
#define napi_release_threadsafe_function napi_release_threadsafe_function_primjs
#define napi_get_threadsafe_function_context \
  napi_get_threadsafe_function_context_primjs

#define napi_fatal_error napi_fatal_error_primjs

#define napi_module_register napi_module_register_primjs

#define napi_resolve_deferred napi_resolve_deferred_primjs
#define napi_reject_deferred napi_reject_deferred_primjs

#define napi_fatal_exception napi_fatal_exception_primjs

#define napi_unref_threadsafe_function napi_unref_threadsafe_function_primjs
#define napi_ref_threadsafe_function napi_ref_threadsafe_function_primjs
#define napi_acquire_threadsafe_function napi_acquire_threadsafe_function_primjs

#define napi_create_date napi_create_date_primjs
#define napi_is_date napi_is_date_primjs
#define napi_get_date_value napi_get_date_value_primjs

#define napi_create_bigint_int64 napi_create_bigint_int64_primjs
#define napi_create_bigint_uint64 napi_create_bigint_uint64_primjs
#define napi_create_bigint_words napi_create_bigint_words_primjs
#define napi_get_value_bigint_int64 napi_get_value_bigint_int64_primjs
#define napi_get_value_bigint_uint64 napi_get_value_bigint_uint64_primjs
#define napi_get_value_bigint_words napi_get_value_bigint_words_primjs
#define napi_get_all_property_names napi_get_all_property_names_primjs
#define napi_would_deadlock napi_would_deadlock_primjs
#define napi_no_external_buffers_allowed napi_no_external_buffers_allowed_primjs
#define napi_cannot_run_js napi_cannot_run_js_primjs

#define napi_create_async_work napi_create_async_work_primjs
#define napi_queue_async_work napi_queue_async_work_primjs
#define napi_cancel_async_work napi_cancel_async_work_primjs
#define napi_delete_async_work napi_delete_async_work_primjs
