name: Publish Pod

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'release tag'
        required: false
        type: string

jobs:
  get-version:
    runs-on: lynx-ubuntu-22.04-medium
    timeout-minutes: 60
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Get Version
        id: get_version
        run: |-
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            version=${{ github.event.inputs.tag }}
          else
            version=$(echo ${{ github.ref }} | awk -F "/" '{print $3}')
          fi
          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ || \
                $version =~ ^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$ || \
                $version =~ ^[0-9]+\.[0-9]+\.[0-9]+-alpha\.[0-9]+$ ]]; then
            echo "Version is valid"
            echo "VERSION=$version" >> $GITHUB_OUTPUT;
          else
            echo "Version is invalid"
            exit 1
          fi

  publish-pod:
    runs-on: macos-13
    needs: get-version
    steps:
      - name: Download Source
        uses: actions/checkout@v4.2.2
      - name: Bundle Install
        run: |-
          SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk bundle install --path .bundle
      - name: Publish to CocoaPods Repo
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.REPO_PRIMJS_COCOAPODS_TRUNK_TOKEN }}
          POD_VERSION: ${{ needs.get-version.outputs.version }}
        run: |-
          pod repo add-cdn trunk https://cdn.cocoapods.org/
          COCOAPODS_TRUNK_TOKEN=$COCOAPODS_TRUNK_TOKEN POD_VERSION=$POD_VERSION pod trunk push PrimJS.podspec  --skip-import-validation --allow-warnings
